### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by CunliangGeng**
Updated README.

### CODE REVIEW

**Review by c-martinez — COMMENTED** [review]
If this PR is just to modify the README, changes in Dockerfile, and other files will cause conflicts when we merge the docker branch. Maybe remove these files from PR?

**Comment by CunliangGeng** [comment]
Sorry, maybe I should not create this new branch from the #28 docker branch. The changes of other files are actually from the docker branch. I guess it will disappear when we merge the PR #28. 
In short, we probably need to first review and merge PR #27, then #28, then this one :-)

**Comment by c-martinez** [comment]
Yes -- you could have created this branch from `dev` and merge it back into `dev` -- well, lets merge them in that order and we should not have conflicts :-)

**Comment by CunliangGeng** [comment]
Thanks! Are they ready to merge? Please approve them if they look good :-)

**Review by c-martinez — APPROVED** [review]

**Comment by c-martinez** [comment]
This could be merged, the PR #28 still has a comment left to discuss.

**Pull request merged**
